name: Update Azure Service Tags

on:
  schedule:
    # Run every night at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build go generator
        run: |
          # Build the Go generator
          cd generate
          go mod download
          go build -o now

      - name: Run go generator
        run: |
          # Generate new YAML files
          ./generate/now -json-input-file data/ServiceTags_Public.json -output data/services

          echo "YAML files generated successfully"

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          TAG_NAME="v$(date +'%Y.%m.%d')"

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          
          echo "Changes to be committed:"
          git diff --stat
          
          git add data/ServiceTags_Public.json data/services/

          git commit -m "Update Azure Service Tags: $TAG_NAME" -m "Automated update from Microsoft's ServiceTags JSON"
          git push
          
          git tag $TAG_NAME
          git push origin $TAG_NAME
